

#ifndef SHADERSOURCE_H
#define SHADERSOURCE_H

#define BILLBOARD_UNIFORMS \
        "uniform mat4 view;\n" \
        "uniform mat4 projection;\n" \
        "uniform vec3 camRight;\n" \
        "uniform vec3 camUp;\n" \
        "uniform vec3 cameraPos;\n"

const char *particleVertexShaderSource =
        "#version 330\n"
        BILLBOARD_UNIFORMS
        "layout (location = 0) in vec2 quadPos;\n"
        "layout (location = 1) in vec2 quadUV;\n"
        "layout (location = 2) in vec3 instPos;\n"
        "layout (location = 3) in float instSize;\n"
        "layout (location = 4) in vec4 instColor;\n"
        "out vec2 vUV;\n"
        "out vec4 vColor;\n"
        "out vec3 vWorldPos;\n"
        "out vec3 vCenterPos;\n"
        "void main()\n"
        "{\n"
        "   vec3 worldPos = instPos + camRight * quadPos.x * instSize + camUp * quadPos.y * instSize;\n"
        "   gl_Position = projection * view * vec4(worldPos, 1.0);\n"
        "   vUV = quadUV;\n"
        "   vColor = instColor;\n"
        "   vWorldPos = worldPos;\n"
        "   vCenterPos = instPos;\n"
        "}\n";

const char *particleFragmentShaderSource =
        "#version 330\n"
        "uniform vec3 fireLightColor;\n"
        "in vec2 vUV;\n"
        "in vec4 vColor;\n"
        "out vec4 Fragment;\n"
        "void main(){\n"
        "   vec2 p = vUV * 2.0 - 1.0;\n"
        "   float r = length(p);\n"
        "   float alpha = clamp(1.0 - r, 0.0, 1.0);\n"
        "   alpha = alpha * alpha;\n" 
        "   float lum = dot(vColor.rgb, vec3(0.2126, 0.7152, 0.0722));\n"
        "   vec3 tint = clamp(fireLightColor, 0.0, 1.0);\n"
        "   vec3 rgb = tint * lum;\n"
        "   Fragment = vec4(rgb, vColor.a * alpha);\n"
        "}\n";


const char* smokeFragmentShaderSource =
        "#version 330\n"
        BILLBOARD_UNIFORMS
        "uniform vec3 fireLightPos;\n"
        "uniform vec3 fireLightColor;\n"
        "uniform float fireLightIntensity;\n"
        "uniform float fireLightRange;\n"
        "uniform float uTime;\n"
        "in vec2 vUV;\n"
        "in vec4 vColor;\n"
        "in vec3 vWorldPos;\n"
        "in vec3 vCenterPos;\n"
        "out vec4 Fragment;\n"
        "float hash(vec3 p){\n"
        "   p = fract(p * 0.3183099 + vec3(0.11, 0.17, 0.23));\n"
        "   p *= 17.0;\n"
        "   return fract(p.x * p.y * p.z * (p.x + p.y + p.z));\n"
        "}\n"
        "float noise(vec3 p){\n"
        "   vec3 i = floor(p);\n"
        "   vec3 f = fract(p);\n"
        "   f = f * f * (3.0 - 2.0 * f);\n"
        "   float n000 = hash(i + vec3(0.0, 0.0, 0.0));\n"
        "   float n100 = hash(i + vec3(1.0, 0.0, 0.0));\n"
        "   float n010 = hash(i + vec3(0.0, 1.0, 0.0));\n"
        "   float n110 = hash(i + vec3(1.0, 1.0, 0.0));\n"
        "   float n001 = hash(i + vec3(0.0, 0.0, 1.0));\n"
        "   float n101 = hash(i + vec3(1.0, 0.0, 1.0));\n"
        "   float n011 = hash(i + vec3(0.0, 1.0, 1.0));\n"
        "   float n111 = hash(i + vec3(1.0, 1.0, 1.0));\n"
        "   float nx00 = mix(n000, n100, f.x);\n"
        "   float nx10 = mix(n010, n110, f.x);\n"
        "   float nx01 = mix(n001, n101, f.x);\n"
        "   float nx11 = mix(n011, n111, f.x);\n"
        "   float nxy0 = mix(nx00, nx10, f.y);\n"
        "   float nxy1 = mix(nx01, nx11, f.y);\n"
        "   return mix(nxy0, nxy1, f.z);\n"
        "}\n"
        "float fbm(vec3 p){\n"
        "   float value = 0.0;\n"
        "   float amp = 0.55;\n"
        "   for (int i = 0; i < 4; ++i) {\n"
        "      value += noise(p) * amp;\n"
        "      p = p * 2.03 + vec3(9.2, 3.7, 5.1);\n"
        "      amp *= 0.5;\n"
        "   }\n"
        "   return value;\n"
        "}\n"
        "vec3 applyPointLight(vec3 lightPos, vec3 lightColor, float lightIntensity, float lightRange, vec3 worldPos, vec3 normal, vec3 viewDir, float density){\n"
        "   vec3 toLight = lightPos - worldPos;\n"
        "   float dist = length(toLight);\n"
        "   if (dist <= 0.0001 || lightIntensity <= 0.0 || lightRange <= 0.0) return vec3(0.0);\n"
        "   vec3 lightDir = toLight / dist;\n"
        "   float falloff = clamp(1.0 - dist / lightRange, 0.0, 1.0);\n"
        "   float diffuse = max(dot(normal, lightDir), 0.0);\n"
        "   float forwardScatter = pow(max(dot(viewDir, lightDir), 0.0), 3.5);\n"
        "   float rim = pow(1.0 - max(dot(normal, viewDir), 0.0), 2.0);\n"
        "   float strength = lightIntensity * falloff * falloff;\n"
        "   return lightColor * strength * (0.18 + diffuse * 0.72 + forwardScatter * (0.8 + density * 0.8) + rim * 0.25);\n"
        "}\n"
        "void main(){\n"
        "   vec2 p = vUV * 2.0 - 1.0;\n"
        "   float r2 = dot(p, p);\n"
        "   if (r2 > 1.0) discard;\n"
        "   float r = sqrt(r2);\n"
        "   vec3 viewDir = normalize(cameraPos - vCenterPos);\n"
        "   float sphereZ = sqrt(max(0.0, 1.0 - r2));\n"
        "   vec3 normal = normalize(camRight * p.x + camUp * p.y + viewDir * sphereZ);\n"
        "   vec3 noisePos = vCenterPos * 1.35 + vec3(p * 1.6, 0.0) + vec3(0.0, uTime * 0.08, uTime * 0.04);\n"
        "   float billow = fbm(noisePos);\n"
        "   float edgeWarp = mix(-0.18, 0.15, billow);\n"
        "   float softShape = smoothstep(1.02, 0.12, r + edgeWarp * 0.35);\n"
        "   float denseCore = smoothstep(0.95, 0.0, r * (0.78 + billow * 0.28));\n"
        "   float wisps = smoothstep(0.28, 0.85, fbm(noisePos * 1.9 + vec3(2.3, 7.1, 4.8)));\n"
        "   float density = clamp(softShape * (0.55 + denseCore * 0.75) * mix(0.72, 1.18, wisps), 0.0, 1.0);\n"
        "   vec3 fireLight = applyPointLight(fireLightPos, fireLightColor, fireLightIntensity, fireLightRange, vWorldPos, normal, viewDir, density);\n"
        "   vec3 ambient = mix(vec3(0.06, 0.065, 0.075), vec3(0.16, 0.17, 0.18), density);\n"
        "   float lum = dot(vColor.rgb, vec3(0.2126, 0.7152, 0.0722));\n"
        "   vec3 tint = clamp(fireLightColor, 0.0, 1.0);\n"
        "   vec3 baseColor = tint * mix(0.22, 0.95, lum) * mix(0.75, 1.05, billow);\n"
        "   vec3 litColor = baseColor * (ambient + fireLight * 0.70);\n"
        "   litColor += fireLight * 0.25;\n"
        "   float alpha = density * vColor.a;\n"
        "   Fragment = vec4(clamp(litColor, 0.0, 1.0), alpha);\n"
        "}\n";

#endif //SHADERSOURCE_H
